###
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "name":"user2",
  "email": "user2@gmail.com",
  "password": "user1234"
}
###
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "email": "AymanAlhaikg@gmail.com",
  "password": "aim0938"
}

### Rest Password
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "email": "AymanAlhaikg@gmail.com"
}
###
POST {{baseUrl}}/auth/verify-code
Content-Type: application/json

{
  "email": "AymanAlhaikg@gmail.com",
  "code": "924852"
}
###
POST {{baseUrl}}/auth/change-password
Content-Type: application/json

{
  "email": "AymanAlhaikg@gmail.com",
  "password": "aim0938"
}
