###
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "hasan",
  "email": "hasan@1.com",
  "role": "user",
  "password": "hasan1234",
  "avatar": "www.photo.com/user/hasan",
  "age": 29,
  "phoneNumber": "+1-202-555-0147",
  "address": "123 Main Street, Springfield",
  "active": true,
  "gender": "male"
}
