###
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.4XDTTmF2BBd6-BuUpmLaAbnZe76Hl739uPzwLgJ2jkQ

{
  "name": "Lamies",
  "email": "6@6.com",
  "password": "hasan1234",
  "active":true

}
###
GET {{baseUrl}}/users?page=3&limit=4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.4XDTTmF2BBd6-BuUpmLaAbnZe76Hl739uPzwLgJ2jkQ

###
GET {{baseUrl}}/users/6913e40cfb3a524cd48eb491
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.4XDTTmF2BBd6-BuUpmLaAbnZe76Hl739uPzwLgJ2jkQ
###
PATCH {{baseUrl}}/users/6913d1a23ebb7e71bbb108d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.4XDTTmF2BBd6-BuUpmLaAbnZe76Hl739uPzwLgJ2jkQ
Content-Type: application/json

{
  "name": "salem"
}
###
DELETE {{baseUrl}}/users/6913d1a23ebb7e71bbb108d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4ifQ.4XDTTmF2BBd6-BuUpmLaAbnZe76Hl739uPzwLgJ2jkQ
